CREATE DATABASE IF NOT EXISTS airline_reservation;
USE airline_reservation;

CREATE TABLE flight
(
  ID INT NOT NULL AUTO_INCREMENT,
  FLIGHT_NUMBER VARCHAR(20) NOT NULL,
  OPERATING_AIRLINES VARCHAR(50) NOT NULL,
  DEPARTURE_CITY VARCHAR(20) NOT NULL,
  ARRIVAL_CITY VARCHAR(20) NOT NULL,
  DATE_OF_DEPARTURE DATE NOT NULL,
  ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE passenger
(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(256),
  LAST_NAME VARCHAR(256),
  MIDDLE_NAME VARCHAR(256),
  EMAIL VARCHAR(50),
  PHONE VARCHAR(20),
  PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE reservation
(
  ID INT NOT NULL AUTO_INCREMENT,
  CHECKED_IN BOOLEAN DEFAULT FALSE,
  NUMBER_OF_BAGS INT,
  PASSENGER_ID INT NOT NULL,
  FLIGHT_ID INT NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES passenger(ID) ON DELETE CASCADE,
  FOREIGN KEY (FLIGHT_ID) REFERENCES flight(ID)
) ENGINE=InnoDB;

-- Flights
INSERT INTO flight (FLIGHT_NUMBER, OPERATING_AIRLINES, DEPARTURE_CITY, ARRIVAL_CITY, DATE_OF_DEPARTURE, ESTIMATED_DEPARTURE_TIME)
VALUES
('AI101', 'Air India', 'Mumbai', 'Delhi', '2026-03-10', '2026-03-10 10:30:00'),
('BA202', 'British Airways', 'London', 'New York', '2026-03-11', '2026-03-11 15:00:00'),
('LH303', 'Lufthansa', 'Frankfurt', 'Tokyo', '2026-03-12', '2026-03-12 20:45:00'),
('UA404', 'United Airlines', 'Chicago', 'Los Angeles', '2026-03-13', '2026-03-13 07:15:00'),
('EK505', 'Emirates', 'Dubai', 'Sydney', '2026-03-14', '2026-03-14 23:50:00');

-- Passengers
INSERT INTO passenger (FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL, PHONE)
VALUES
('Esther', 'Kandiwa', 'L', 'esther.k@example.com', '+35312345678'),
('Betzalel', 'Ampo', 'T', 'betzalel.a@example.com', '+35387654321'),
('Ariel', 'Kandiwa', 'M', 'ariel.k@example.com', '+35311223344'),
('John', 'Doe', 'P', 'john.doe@example.com', '+35399887766'),
('Jane', 'Smith', 'Q', 'jane.smith@example.com', '+35355443322');

-- Reservations
INSERT INTO reservation (CHECKED_IN, NUMBER_OF_BAGS, PASSENGER_ID, FLIGHT_ID)
VALUES
(FALSE, 2, 1, 1),
(TRUE, 1, 2, 2),
(FALSE, 0, 3, 3),
(TRUE, 3, 4, 1),
(FALSE, 2, 5, 5);


